version: '3.9'

services:
  frontend:
    image: ghcr.io/blockscout/frontend:v1.28.0-alpha
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
